

//USE LOCAL SERVER WHILE DEVELOPING AS FIREBASE CHARGE WHEN DEPLOY THE FUNCTION

export const STRIPE_FIREBASE_SERVER="http://127.0.0.1:5001/digital-scrap-dc471/us-central1/completePaymentWithStripe"